dist: trusty
sudo: false
language: node_js
node_js:
  - node

cache:
  directories:
    - ./node_modules

before_install:
-  openssl aes-256-cbc -K $encrypted_e4e84a977059_key -iv $encrypted_e4e84a977059_iv
 -in firebase-leafer-key.json.enc -out src/notification/firebase-leafer-key.json -d

install:
  - npm install

script:
  - npm run test

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
  - provider: heroku
    api_key:
      secure: IFCPKX9uz1lhBK4tUoXyrpa28LWA3KjXImBjzj1eyKDWyizwPJnHtxuFWjQ0ZM53+9YwTywkkxAHBTm1mKw7YCYeIUu8uT4PWC6ZBC0knAgLRuuzXw3kGPGSoXqEy7bhPtbq89cw9CmnT/LSjnpBbxruNs2/ykuavjFrZ9v0eIXBBUM8BTjFpnVot7zlSEY0L3ehPrAHS/jn4nRFGCIL1wS8S6m9R/GLXkqQ58NASXo/4xVjiWvW9jjeQ98ovjbB73Z9lNLO460Vil6uylOd77JjlfkmJLjA/b/zCTl5IM0FaRKobkdq+3CxDPzEZhWgpBFqh1Z053QJDc+gUUL8BIj3vpsYumpVqRXtvoB5nlPtzKRWAcAgLE7tl5lW+xAVvz0kfYvFNmeNwGIBvnu+Lk+WX2Z2dYCapaL7xkAVOnUsXO4DE4tOWgJCiKog6Z13SV1/dQbp3fOqeP8yFA0oZYhDc8HOtGpgfXudgRBBgsf8iveUSQg9dF5ZIl6qzFCYQAEeOM2LGPxsZGXQ9YCHHYaaClMPDt8/tX4N8q+53FDms9TBtJMAjPl0T9o5CEvnin+wFuF4CDH3lg9mR+w1AOYEmVFZEf0shXQ8KjmwzdZGf94/6RDWlQwVjoM1CzgM4E3GqQcsm0DMzUIQeoNhUBpQFRJFag4BIUZf3lPUNCM=
    app:
      develop: leafer-rest-api-dev
      master: leafer-rest-api-prod

notifications:
  email: false